// Reviewer-owned shared harness for the sourcing evaluator (sourcing-v1, L0).
//
// Nothing here touches the network: every check injects a deterministic
// transport (`fetchImpl`) and lookup (`lookupImpl`) into the exported repo
// surfaces. The harness is deliberately small: it builds fake transports from
// data, records every request in order, and classifies policy vs content
// requests so denial semantics can be asserted structurally.
//
// Do not edit this file after the freeze (see docs/BENCHMARK-sourcing-v1.md).

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const HELPERS_DIR = path.dirname(fileURLToPath(import.meta.url));
export const TESTS_DIR = path.dirname(HELPERS_DIR);
export const REPO_ROOT = path.dirname(TESTS_DIR);

// Policy codes fixed by the plan's decision table. `policy_absent` is the one
// allow-side code; a denial must match /^policy_/ without being an allow code.
export const POLICY_CODES = Object.freeze({
  absent: 'policy_absent',
  invalid: 'policy_invalid',
  unreadable: 'policy_unreadable',
  unreachable: 'policy_unreachable'
});

const POLICY_ALLOW_CODES = new Set([POLICY_CODES.absent]);

export function errorCode(error) {
  return String(error?.code || error?.name || '');
}

export function isDenialCode(code) {
  const value = String(code || '');
  return /^policy_/.test(value) && !POLICY_ALLOW_CODES.has(value);
}

export function fixturePath(rel) {
  return path.join(TESTS_DIR, 'fixtures', 'sourcing', rel);
}

export function readFixture(rel) {
  return JSON.parse(readFileSync(fixturePath(rel), 'utf8'));
}

export function readRepoFile(rel) {
  return readFileSync(path.join(REPO_ROOT, rel), 'utf8');
}

// Copy an evaluator fixture into the isolated PLUGIN_DATA so the repo's own
// PLUGIN_DATA boundary rules apply unchanged.
export function stageFixture(dataDir, rel, fixtureRel) {
  const abs = path.join(dataDir, rel);
  mkdirSync(path.dirname(abs), { recursive: true });
  copyFileSync(fixturePath(fixtureRel), abs);
  return abs;
}

// Any public address will do: the checks never reach the network.
export function publicLookup(address = '93.184.216.34') {
  return async () => [{ address, family: 4 }];
}

export function originOf(url) {
  return new URL(String(url)).origin;
}

export function robotsUrlOf(url) {
  return `${originOf(url)}/robots.txt`;
}

export function isPolicyRequest(url) {
  return /\/robots\.txt(\?|#|$)/.test(String(url));
}

// Transport presets stand in for real network failures. The product only has to
// fail closed on any throw; the distinguishable codes are what a real
// implementation would see from undici.
const THROW_PRESETS = Object.freeze({
  timeout: () => Object.assign(new Error('policy fetch timed out'), { name: 'TimeoutError', code: 'UND_ERR_CONNECT_TIMEOUT' }),
  dns: () => {
    const error = Object.assign(new Error('getaddrinfo ENOTFOUND policy host'), { name: 'TypeError', code: 'ENOTFOUND' });
    error.cause = { code: 'ENOTFOUND', message: 'getaddrinfo ENOTFOUND' };
    return error;
  },
  tls: () => {
    const error = Object.assign(new Error('certificate has expired'), { name: 'TypeError', code: 'CERT_HAS_EXPIRED' });
    error.cause = { code: 'CERT_HAS_EXPIRED', message: 'certificate has expired' };
    return error;
  },
  connrefused: () => {
    const error = Object.assign(new Error('connect ECONNREFUSED'), { name: 'TypeError', code: 'ECONNREFUSED' });
    error.cause = { code: 'ECONNREFUSED', message: 'connect ECONNREFUSED' };
    return error;
  }
});

export function thrownFrom(spec) {
  if (typeof spec === 'string') {
    const preset = THROW_PRESETS[spec];
    if (!preset) throw new Error(`unknown throw preset: ${spec}`);
    return preset();
  }
  const error = new Error(String(spec.message || spec.name || 'transport failure'));
  error.name = String(spec.name || 'Error');
  error.code = String(spec.code || spec.name || 'transport_error');
  return error;
}

function matchesRule(rule, url) {
  if (typeof rule.match === 'string') return rule.match === url;
  if (typeof rule.prefix === 'string') return url.startsWith(rule.prefix);
  if (typeof rule.contains === 'string') return url.includes(rule.contains);
  if (typeof rule.re === 'string') return new RegExp(rule.re).test(url);
  return false;
}

function validateRules(rules) {
  for (const [index, rule] of rules.entries()) {
    const keyed = ['match', 'prefix', 'contains', 're'].some(key => typeof rule[key] === 'string');
    if (!keyed) throw new Error(`transport rule ${index} has no match/prefix/contains/re selector`);
  }
}

function normalizeHeaders(headers) {
  const out = {};
  if (!headers) return out;
  if (typeof headers.entries === 'function') {
    for (const [key, value] of headers.entries()) out[String(key).toLowerCase()] = String(value);
    return out;
  }
  for (const [key, value] of Object.entries(headers)) out[String(key).toLowerCase()] = String(value);
  return out;
}

/**
 * Build a deterministic fake transport. Rules are matched in order; the first
 * hit is served. An unmatched URL throws `unexpected_request`, so "no content
 * request was ever made" is asserted by the request log, not by silence.
 */
export function makeTransport(rules = []) {
  validateRules(rules);
  const requests = [];

  const fetchImpl = async (url, init = {}) => {
    const href = String(url);
    const headers = normalizeHeaders(init.headers);
    requests.push({ index: requests.length, url: href, method: String(init.method || 'GET').toUpperCase(), headers });

    const rule = rules.find(item => matchesRule(item, href));
    if (!rule) throw Object.assign(new Error(`no transport rule for ${href}`), { code: 'unexpected_request' });
    if (rule.throw) throw thrownFrom(rule.throw);

    const status = Number.isFinite(Number(rule.status)) ? Number(rule.status) : 200;
    const body = rule.body == null ? '' : String(rule.body);
    const responseHeaders = { ...(rule.headers || {}) };
    if (!Object.keys(responseHeaders).some(key => key.toLowerCase() === 'content-type')) {
      responseHeaders['content-type'] = 'text/plain';
    }
    return {
      status,
      ok: status >= 200 && status < 300,
      url: href,
      headers: new Headers(responseHeaders),
      async text() { return body; },
      async json() { return JSON.parse(body); }
    };
  };

  const transport = {
    fetchImpl,
    requests,
    urls: () => requests.map(request => request.url),
    count: () => requests.length,
    indexOf: url => requests.findIndex(request => request.url === String(url)),
    requested: url => requests.some(request => request.url === String(url)),
    policyRequests: () => requests.filter(request => isPolicyRequest(request.url)),
    policyRequestsFor: origin => requests.filter(request => request.url === `${origin}/robots.txt`),
    contentRequestsFor: origin => requests.filter(request => request.url.startsWith(origin) && !isPolicyRequest(request.url)),
    forUrl: (url, options = {}) => requests.filter(request => String(url).split('?')[0] === request.url.split('?')[0] && (options.query == null || request.url.includes(String(options.query))))
  };
  return transport;
}

// True when every request the transport ever saw was a policy request.
export function onlyPolicyRequests(transport) {
  return transport.requests.length === transport.policyRequests().length;
}

export function dataDirFiles(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  const walk = current => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) walk(abs);
      else if (entry.isFile()) out.push(path.relative(dir, abs));
    }
  };
  walk(dir);
  return out.sort();
}

// The gate derives its policy-cache root from PLUGIN_DATA (the value the host
// expands into mcp.json's --data argument). Set it around the call, restore it
// after, and never leak it into the next test.
export async function withPluginData(dir, fn) {
  const previous = process.env.PLUGIN_DATA;
  if (dir === null || dir === undefined) delete process.env.PLUGIN_DATA;
  else process.env.PLUGIN_DATA = String(dir);
  try {
    return await fn();
  } finally {
    if (previous === undefined) delete process.env.PLUGIN_DATA;
    else process.env.PLUGIN_DATA = previous;
  }
}

export function jsonText(value) {
  try {
    return JSON.stringify(value) ?? String(value);
  } catch {
    return String(value);
  }
}

// Value-level provenance check: nesting cannot hide a preserved field.
export function valuePresent(value, needle) {
  return jsonText(value).includes(String(needle));
}

export function hasKeyDeep(value, key, depth = 0) {
  if (depth > 12) return false;
  if (Array.isArray(value)) return value.some(item => hasKeyDeep(item, key, depth + 1));
  if (value && typeof value === 'object') {
    if (Object.prototype.hasOwnProperty.call(value, key)) return true;
    return Object.values(value).some(item => hasKeyDeep(item, key, depth + 1));
  }
  return false;
}

// Run a call that is expected to reject, without losing the failure detail.
export async function settle(fn) {
  try {
    return { ok: true, value: await fn() };
  } catch (error) {
    return { ok: false, value: null, error, code: errorCode(error), message: String(error?.message || error) };
  }
}
